package com.andreibel.shortlink.moduels;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity class representing a click event for a URL mapping.
 * Maps to the 'click_event' table in the database.
 */
@Entity
@Getter
@Setter
@Table(name = "click_event")
public class ClickEvent {
    /**
     * Unique identifier for the click event.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Date when the click occurred.
     */
    private LocalDateTime clickDate;

    /**
     * Reference to the URL mapping associated with this click event.
     * Many-to-one relationship; loaded lazily.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "url_mapping_id", nullable = false)
    private UrlMapping urlMapping;
}