package com.andreibel.shortlink.moduels;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Entity class representing a user in the system.
 * Maps to the 'users' table in the database.
 *
 * Fields:
 * <ul>
 *   <li>id - Primary key, auto-generated</li>
 *   <li>email - User's email address, must be unique and not null</li>
 *   <li>username - User's display name</li>
 *   <li>password - User's hashed password</li>
 *   <li>role - User's role, defaults to 'ROLE_USER'</li>
 * </ul>
 */
@Entity
@Getter
@Setter
@Table(name = "users")
public class User {
    /**
     * Unique identifier for the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User's email address.
     * Must be unique and not null.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * User's display name.
     */
    private String username;

    /**
     * User's hashed password.
     */
    private String password;

    /**
     * User's role in the system.
     * Defaults to 'ROLE_USER'.
     */
    private String role = "ROLE_USER";
}